version: '3'
services:
  jenkins:
    build: 
      # build from Dockerfile
        context: ./jenkins-master
        dockerfile: dockerfile
    networks:
      - jenkins
    ports:
      - '8080:8080'
      - '9080:9080'
    volumes:
      - 'jenkins_data:/var/jenkins_home'
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  jenkins:
volumes:
  jenkins_data: