FROM mcr.microsoft.com/powershell:lts-debian-buster-slim

ARG DEBIAN_FRONTEND=noninteractive
ENV AWS_ACCESS_KEY_ID=AKIA46EDMOPGY7P7KKKY
ENV AWS_SECRET_ACCESS_KEY=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

WORKDIR ~/

RUN apt-get update && \
    apt-get install -y apt-transport-https ca-certificates curl gnupg2 software-properties-common unzip && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable" && \
    apt-get update && \
    apt-get install -y docker-ce docker-ce-cli containerd.io && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install

ENTRYPOINT tail -f /dev/null